version: "3.9"
services:
  postgres:
    image: postgres:15.4
    container_name: dogrepositorydb
    hostname: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dogrepositorydb
    ports:
      - "5432:5432"
