version: "3.9"
services:

  postgres:
    image: postgres:16.2
    container_name: dogrepositorydb_render
    hostname: localhost
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dogrepositorydb
    ports:
      - "5432:5432"