server:
  address: 0.0.0.0
  port: ${PORT:8080}
spring:
  flyway:
    baselineOnMigrate: true
  config:
    import: optional:file:.env[.properties]
  jpa:
    properties:
      hibernate:
        show-sql: ${HIBERNATE_SHOW_SQL:true}
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:dpg-cns50mf109ks73fj425g-a}:${DATABASE_PORT:5432}/${POSTGRES_DB:dogrepositorydb}
    username: ${POSTGRES_USER:ines}
    password: ${POSTGRES_PASSWORD:22c4yghuivDQ2RbVJB3alUHI2jx2dz9P}
