server:
  address: 0.0.0.0
  port: ${PORT:8080}
spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    properties:
      hibernate:
        show-sql: ${HIBERNATE_SHOW_SQL:true}
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${POSTGRES_DB:dogrepositorydb}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:password}